server:
  port: 8080

spring:
  #配置数据源
  driver-class-name: com.mysql.cj.jdbc.Driver
  url:jdbc: mysql://localhost:3306/xxx?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
  username: root
  password: root1234
  hikari:
    pool-name: DateHikariCP
    minmum-idle: 5
    idle-timeout: 600000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 1800000
    connection-timout: 30000
    connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxx.server.pojo
  # 关闭驼峰命名
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.xxx.server.mapper: debug
